# Generated by Django 5.2.7 on 2025-11-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
