# Generated by Django 5.2.8 on 2025-11-16 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigo_area', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('codigo_sede', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sede',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('codigo_inventario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('proceso', models.CharField(blank=True, max_length=80, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('codigo_ips', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_ecri', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('motivo_cambio_ubi', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=80, null=True)),
                ('modelo', models.CharField(blank=True, max_length=120, null=True)),
                ('serie', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('clasificacion_misional', models.CharField(blank=True, max_length=80, null=True)),
                ('clasificacion_ips', models.CharField(blank=True, max_length=50, null=True)),
                ('clasificacion_riesgo', models.CharField(blank=True, max_length=50, null=True)),
                ('registro_invima', models.CharField(blank=True, max_length=100, null=True)),
                ('modificacionUbi', models.CharField(blank=True, max_length=50, null=True)),
                ('modificacionactivo', models.CharField(blank=True, max_length=50, null=True)),
                ('modificacionCodigo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, db_column='area_codigo', null=True, on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.area')),
                ('sede', models.ForeignKey(blank=True, db_column='sede_codigo', null=True, on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.sede')),
            ],
            options={
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hoja_vida', models.BooleanField(default=False)),
                ('registro_importacion', models.BooleanField(default=False)),
                ('manual_operacion', models.BooleanField(default=False)),
                ('manual_mantenimiento', models.BooleanField(default=False)),
                ('guia_uso', models.BooleanField(default=False)),
                ('instructivo_rapido', models.BooleanField(default=False)),
                ('protocolo_mto_prev', models.BooleanField(default=False)),
                ('frecuencia_metrologica_fabricante', models.CharField(blank=True, max_length=80, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(db_column='equipo_codigo', on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.equipo')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='CondicionesFuncionamiento',
            fields=[
                ('id_condiciones', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('voltaje', models.CharField(blank=True, max_length=80, null=True)),
                ('corriente', models.CharField(blank=True, max_length=80, null=True)),
                ('humedad_relativa', models.CharField(blank=True, max_length=80, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=80, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=120, null=True)),
                ('peso', models.CharField(blank=True, max_length=50, null=True)),
                ('otros', models.CharField(blank=True, max_length=120, null=True)),
                ('equipo', models.ForeignKey(db_column='equipo_codigo', on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.equipo')),
            ],
            options={
                'db_table': 'condiciones_funcionamiento',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tiempo_vida_anos', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('propietario', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('garantia', models.BooleanField(default=False)),
                ('fecha_caducidad_garantia', models.DateField(blank=True, null=True)),
                ('forma_adquisicion', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=40, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=60, null=True)),
                ('equipo', models.ForeignKey(db_column='equipo_codigo', on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.equipo')),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.CreateModel(
            name='MetrologiaAdministrativa',
            fields=[
                ('id_metrologia_adm', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mantenimiento', models.BooleanField(default=False)),
                ('frecuencia_mantenimiento_anual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calibracion', models.BooleanField(default=False)),
                ('frecuencia_calibracion_anual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('equipo', models.ForeignKey(db_column='equipo_codigo', on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.equipo')),
            ],
            options={
                'db_table': 'metrologia_administrativa',
            },
        ),
        migrations.CreateModel(
            name='MetrologiaTecnica',
            fields=[
                ('id_metrologia_tecnica', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('magnitud', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_equipo', models.CharField(blank=True, max_length=255, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('error_maximo_permitido', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo', models.ForeignKey(db_column='equipo_codigo', on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.equipo')),
            ],
            options={
                'db_table': 'metrologia_tecnica',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='sede',
            field=models.ForeignKey(db_column='sede_codigo', on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.sede'),
        ),
    ]
