# Generated by Django 5.2.8 on 2025-12-03 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIEquipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ubicacion',
            },
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='area',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='modificacionCodigo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='motivo_cambio_ubi',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='proceso',
        ),
        migrations.AddField(
            model_name='historial',
            name='valor_compra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_baja',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='registro_invima',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_adquisicion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_caducidad_garantia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_fabricacion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tiempo_vida_anos',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrologiaadministrativa',
            name='frecuencia_calibracion_anual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metrologiaadministrativa',
            name='frecuencia_mantenimiento_anual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metrologiatecnica',
            name='error_maximo_permitido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metrologiatecnica',
            name='magnitud',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metrologiatecnica',
            name='resolucion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='RegistroActividades',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=140)),
                ('tipo_modificacion', models.CharField(max_length=200)),
                ('fecha_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('motivoCambio', models.CharField(blank=True, max_length=355, null=True)),
                ('origenUbi', models.CharField(blank=True, max_length=250, null=True)),
                ('destinoUbi', models.CharField(blank=True, max_length=250, null=True)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('equipo', models.ForeignKey(db_column='equipo_codigo', on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.equipo')),
            ],
            options={
                'db_table': 'registro_actividades',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo_servicio', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('sede', models.ForeignKey(db_column='sede_codigo', on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.sede')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='servicio',
            field=models.ForeignKey(blank=True, db_column='servicio_codigo', null=True, on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.servicio'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, db_column='ubicacion_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='APIEquipos.ubicacion'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
