# Generated by Django 5.2.8 on 2025-12-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIEquipos', '0002_ubicacion_remove_equipo_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividades',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
